import * as C from './core.js';
import {SharedStore} from './api.js';
import {parseGroupWorkbook,previewGroupImport,applyGroupImport} from './group-import.js';
import {downloadExcel,downloadTeamCSV} from './export.js';
import {MEMBER_COLUMNS,checkColumnId,columnCheckId,rosterColumns,normalizeColumns,filtersForColumns,sortKeysForColumns,checkFilterMatches} from './member-view.js';
const $=s=>document.querySelector(s),store=new SharedStore();
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const N=x=>x==null?'—':Number(x).toLocaleString('ja-JP');
const DT=s=>s?new Date(s).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'—';
let state=null,revision=0,updatedAt='',season='s5',page='dashboard',detailId='',teamDetailId='',returnFromDetail='members',demo=false,busy=false,dirty=false;
let groupImportPreview=null,groupImportFile='',importData=null,importRows=[],logs=[],logsLoaded=false,query='',teamFilter='',sortKey='rankName',sortDescending=false,memberColumns=null,roleFilter='all',groupFilter='',checkFilters={},presenceFilter='',reviewFilter='pending',reviewQuery='',listPage=0,pendingSave=null;
const pageNames={dashboard:'一門のようす',members:'メンバー名簿',import:'週次CSV取込',teams:'分隊名簿',management:'名簿・分隊の管理',review:'移行・照合確認',audit:'変更履歴',settings:'保存と設定'};
const fieldNames={name:'ゲーム内名前',discordName:'Discord名前',discordId:'Discord ID',originContext:'元所属・経緯（原文）',origin:'元所属',joinHistory:'加入経緯',note:'メモ',role:'役割',teamHistory:'隊履歴',nameHistory:'名前履歴',memberships:'シーズン所属',presenceEvents:'一時離脱・復帰履歴',checks:'運営チェック',memberId:'紐付け先',snapshots:'週次CSV',legacy:'過去実績',formations:'隊編成',meta:'全体設定',seasons:'シーズン',aliases:'別名',issues:'要確認',sources:'元資料',contributions:'貢献履歴'};
const fmtDiff=x=>x==null?'（なし）':typeof x==='object'?JSON.stringify(x,null,2):String(x);
function toast(msg,error=false){const el=$('#toast');el.textContent=msg;el.classList.toggle('error',error);el.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.display='none',error?14000:5000);}
function download(name,data,type='application/json'){const blob=new Blob([typeof data==='string'||data instanceof Uint8Array?data:JSON.stringify(data,null,2)],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),15000);}
function options(items,value){return items.map(([v,label])=>`<option value="${E(v)}" ${v===value?'selected':''}>${E(label)}</option>`).join('');}
function memberOptions(value=''){return options([['','既存メンバーを選択'],...Object.values(state.members).sort((a,b)=>a.name.localeCompare(b.name,'ja')).map(m=>[m.id,m.name+' · '+m.id.slice(0,6)])],value);}
function seasonOptions(){return options(Object.values(state.seasons).map(x=>[x.id,x.name]),season);}
function button(text,action,extra='',klass=''){return `<button class="${klass}" data-action="${action}" ${extra}>${E(text)}</button>`;}
function notice(text,kind=''){return `<div class="notice ${kind}">${E(text)}</div>`;}
function stat(label,value,sub){return `<div class="card"><div class="label">${E(label)}</div><div class="number">${E(value)}</div><small>${E(sub)}</small></div>`;}
function header(title,sub,actions=''){return `<div class="heading"><div><div class="eyebrow">HEKIRYU GEKKYO / ${E(state.seasons[season]?.name)}</div><h1>${E(title)}</h1><p class="subline">${E(sub)}</p></div><div class="actions">${actions}</div></div>`;}
function chart(points,label,color='#397f75'){const vals=points.filter(p=>p.value!=null);if(!vals.length)return `<div class="empty">${E(label)}の記録がまだありません。</div>`;
 const w=640,h=220,left=64,right=18,top=16,bottom=40,max=Math.max(...vals.map(p=>p.value),1);const x=i=>points.length===1?(w+left-right)/2:left+i*(w-left-right)/(points.length-1),y=v=>h-bottom-v/max*(h-top-bottom);let lines='';
 for(let i=0;i<=3;i++){const v=max*i/3,yy=y(v);lines+=`<line class="grid" x1="${left}" y1="${yy}" x2="${w-right}" y2="${yy}"/><text x="${left-10}" y="${yy+4}" text-anchor="end">${E(v>=10000?(v/10000).toFixed(v>=100000?0:1)+'万':Math.round(v))}</text>`;}
 let d='',open=false;points.forEach((p,i)=>{if(p.value==null){open=false;return;}d+=(open?' L':' M')+x(i)+','+y(p.value);open=true;});
 const labels=points.map((p,i)=>i===0||i===points.length-1||i%Math.max(1,Math.ceil(points.length/5))===0?`<text x="${x(i)}" y="${h-12}" text-anchor="middle">${E(p.date.slice(5))}</text>`:'').join('');
 return `<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${E(label)}">${lines}<path d="${d}" fill="none" stroke="${color}" stroke-width="2.5"/>${points.map((p,i)=>p.value==null?'':`<circle cx="${x(i)}" cy="${y(p.value)}" r="4" fill="${color}"><title>${E(p.date)} : ${N(p.value)}</title></circle>`).join('')}${labels}</svg><p class="unitnote">${E(label)} · 欠測値は線をつなぎません。数値は下の表で確認できます。</p>`;}
function sumMetric(rows,key){const present=rows.filter(r=>r[key]!=null);return present.length?present.reduce((a,r)=>a+r[key],0):null;}
function operator(){return sessionStorage.getItem('clan-ledger-operator')||'';}
function modalForm(title,body,submit='保存する'){return new Promise(resolve=>{const d=$('#modal');d.innerHTML=`<form id="modal-form"><h2>${E(title)}</h2>${body}<div class="actions"><button type="button" id="modal-cancel">キャンセル</button><button class="primary" type="submit">${E(submit)}</button></div></form>`;
 const finish=value=>{d.close();d.oncancel=null;resolve(value);};d.oncancel=e=>{e.preventDefault();finish(null);};$('#modal-cancel').onclick=()=>finish(null);$('#modal-form').onsubmit=e=>{e.preventDefault();finish(Object.fromEntries(new FormData(e.target)));};d.showModal();});}
async function ensureOperator(){if(operator())return operator();const data=await modalForm('操作者名を入力',`<p class="subline">変更履歴に残る表示名です。「お菊」「○△」など、わかる名前を入力してください。</p><label>操作者名<input name="operator" required maxlength="80" autocomplete="off" autofocus></label>`,'この名前で操作');if(!data)return null;const name=data.operator.trim();if(!name)throw new Error('操作者名を入力してください');if(!demo)await store.changeOperator(name);else sessionStorage.setItem('clan-ledger-operator',name);return name;}
async function save(next,kind,summary,imported=[]){if(demo)throw new Error('読取プレビューです。共有DBへログインして編集してください');if(busy)return false;C.validateState(next);const op=await ensureOperator();if(!op)return false;busy=true;document.body.classList.add('busy');
 const signature=JSON.stringify([next,revision,op,kind,summary,imported]);if(!pendingSave||pendingSave.signature!==signature)pendingSave={signature,id:C.uid()};
 try{const res=await store.save(next,revision,op,kind,summary,imported,pendingSave.id);state=C.validateState(res.state);revision=res.revision;updatedAt=res.updatedAt;pendingSave=null;dirty=false;logsLoaded=false;toast('共有DBへ保存しました');return true;}
 catch(e){toast(e.message,true);return false;}finally{busy=false;document.body.classList.remove('busy');}}
async function refresh(manual=false){if(demo)return;if(dirty||importRows.length){if(!manual)return;if(!confirm('編集中の入力・CSV照合を閉じ、共有DBの最新データを読み直しますか？'))return;}const res=await store.load();const first=!state;if(first||res.revision!==revision||manual){state=C.validateState(res.state);revision=res.revision;updatedAt=res.updatedAt;dirty=false;logsLoaded=false;if(manual){importRows=[];importData=null;groupImportPreview=null;}if(first||!state.seasons[season])season=state.meta.activeSeasonId;render();}if(manual)toast('最新データを読み込みました');}
function loginView(error=''){const configured=store.config.url&&store.config.key;$('#app').innerHTML=`<main class="login"><div class="eyebrow">MEMBERS & WEEKLY RECORDS</div><h1 class="title">一門手帳</h1><p class="subline">碧龍月梟のメンバーと、積み重なる記録。</p><div class="panel" style="margin-top:24px">${error?notice(error,'error'):''}${!configured?notice(store.configError||'セットアップ担当者がconfig.jsへ接続先を設定してから公開してください。手順はREADMEにあります。','error'):''}<form id="login-form" class="fields"><label>一門共通の合言葉<input name="passphrase" type="password" autocomplete="off" required maxlength="256" aria-describedby="phrase-help"></label><p class="unitnote" id="phrase-help">幹部内で共有された合言葉を入力してください。</p><label>今回の操作者名<input name="operator" autocomplete="off" required maxlength="80" placeholder="お菊、○△、□□…"></label><p class="unitnote">変更履歴に残る自己申告の名前です。正式なゲーム内名と同じでなくても構いません。</p><button class="primary" type="submit" ${!configured?'disabled':''}>共有DBにログイン</button></form></div><div class="panel"><h3>導入前に名簿を確認</h3><p class="subline">初期データやバックアップを選ぶと、読取専用で画面を確認できます。共有DBには保存されません。</p><label style="margin-top:15px">JSONファイルを選択<input id="preview-file" type="file" accept=".json"></label></div><footer>v${C.VERSION} · 操作者名と利用セッションはこのタブで保持（最長12時間）<br>人物データの正本は共有DBです。</footer></main>`;}
async function reconnect(){if(demo)return;const d=await modalForm('再ログイン',`<p class="subline">入力中の内容を保ったまま接続し直します。接続後、保存操作を再度行ってください。</p><div class="fields"><label>一門共通の合言葉<input name="passphrase" type="password" autocomplete="off" maxlength="256" required></label><label>今回の操作者名<input name="operator" value="${E(operator())}" maxlength="80" required></label></div>`,'接続する');if(!d)return;try{await store.login(d.passphrase,d.operator);toast('接続しました。保存・再読込などの操作を再度行ってください。');document.querySelectorAll('[data-action="operator"]').forEach(b=>b.textContent='操作者：'+operator());}finally{d.passphrase='';$('#modal').innerHTML='';}}

function render(){if(!state){loginView();return;}$('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">一門手帳<small>碧龍月梟 · OPERATIONS</small></div><nav class="nav" aria-label="メインメニュー"><div class="nav-caption">一門の情報</div>${['dashboard','members','teams'].map(key=>button(pageNames[key],'nav',`data-page="${key}"`,page===key?'active':'')).join('')}<div class="nav-divider"></div><div class="nav-caption">管理・記録</div>${['management','import','review','audit','settings'].map(key=>button(pageNames[key],'nav',`data-page="${key}"`,page===key?'active':'')).join('')}</nav><div class="sidefoot"><span>記録をつなぎ、人を知る。</span><small>v${C.VERSION} / ${demo?'読取プレビュー':'共有データ'}</small>${button('ログアウト','logout')}</div></aside><div class="workspace"><header class="topbar"><div class="row"><select id="season-select" aria-label="表示シーズン">${seasonOptions()}</select><span class="status">${demo?'読取プレビュー・保存なし':`共有DB · 更新 ${E(DT(updatedAt))} · v${revision}`}</span></div><div class="actions">${button('操作者：'+(operator()||'未設定'),'operator')}${!demo?button('再ログイン','reconnect'):''}${button('再読込','refresh')}${button(demo?'プレビュー終了':'ログアウト','logout')}</div></header><main class="main">${demo?notice('読取専用のプレビューです。この画面のデータは共有DBに保存されていません。'):''}${pageContent()}</main></div></div>`;
 if(page==='members'&&!detailId)renderMemberRows();if(page==='review')renderReviewRows();if(page==='import'&&importRows.length)renderImportRows();if(page==='audit'&&!logsLoaded)loadLogs();}
function pageContent(){if(page==='dashboard')return dashboard();if(page==='members')return detailId?detail():membersView();if(page==='import')return importView();if(page==='teams')return teamDetailId?teamRecordView():teamsView();if(page==='management')return managementView();if(page==='review')return reviewView();if(page==='audit')return auditView();return settingsView();}
function teamMarker(id){const c=C.teamColor(id);return `<span class="team-mark ${id==='team4'?'white':''}" style="--mark:${E(c.hex)}" title="${E(c.name)}備え" aria-label="${E(c.name)}"></span>`;}
function teamTitle(id,name){return teamMarker(id)+' '+E(name);}
function percentChange(now,prev){if(now==null||prev==null)return '前週比較なし';if(!prev)return now===0?'前週比 0%':'前週0のため比率なし';const pct=(now-prev)/prev*100;return `前週比 ${pct>=0?'+':''}${pct.toFixed(1)}%`;}
function metricValue(stats,key){return stats?.[key]?.total??null;}
function teamComparisonChart(series,key){const pts=series.map(x=>x.series.map(v=>({date:v.date,value:metricValue(v,key)})));
 const any=pts.flat().some(p=>p.value!=null);if(!any)return '<div class="empty">隊ごとの週次記録がまだありません。</div>';
 const w=680,h=230,left=62,right=22,top=18,bottom=38,n=Math.max(...pts.map(p=>p.length));const values=pts.flat().filter(p=>p.value!=null).map(p=>p.value),max=Math.max(1,...values);const x=i=>n<=1?(left+w-right)/2:left+i*(w-left-right)/(n-1),y=v=>h-bottom-v/max*(h-top-bottom);
 const grid=[0,1,2,3].map(i=>{const num=max*i/3,yy=y(num);return `<line class="grid" x1="${left}" y1="${yy}" x2="${w-right}" y2="${yy}"/><text x="${left-9}" y="${yy+4}" text-anchor="end">${E(num>=10000?(num/10000).toFixed(1)+'万':Math.round(num))}</text>`;}).join('');
 const lines=pts.map((points,i)=>{let d='',open=false;points.forEach((p,j)=>{if(p.value==null){open=false;return;}d+=(open?' L':' M')+x(j)+','+y(p.value);open=true;});return `<path d="${d}" fill="none" stroke="${E(C.teamColor(series[i].id).hex)}" stroke-width="${series[i].id==='team4'?4:2.5}" ${series[i].id==='team4'?'stroke-dasharray="7 4"':''}/>`;}).join('');
 const dates=pts[0]||[];const labels=dates.map((p,i)=>i===0||i===n-1||i%Math.max(1,Math.ceil(n/5))===0?`<text x="${x(i)}" y="${h-11}" text-anchor="middle">${E(p.date.slice(5))}</text>`:'').join('');
 return `<svg class="chart team-comparison-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="隊別${E(key==='merit'?'戦功':'活躍度')}推移">${grid}${lines}${labels}</svg><p class="unitnote">${series.map(g=>teamTitle(g.id,g.name)).join('　')} · 白隊は破線で表示。欠測は0として扱いません。</p>`;}
function dashboard(){const ms=membersInSeason(),snaps=C.orderedSnapshots(state,season),last=snaps.at(-1),rows=last?.rows||[],defs=C.teamDefs(state,season);
 const series=defs.map(t=>({...t,series:C.teamSeries(state,season,t.id)}));const latest=defs.map(t=>({...t,stats:C.teamStats(state,season,t.id,last)}));
 const rowsUnknown=(last?.rows||[]).filter(r=>!defs.some(t=>t.id===C.teamId(state,season,C.teamAt(state.members[r.memberId],season,last.date))));
 return header('一門のようす',last?`最新の記録：${last.date} · ${rows.length}名分`:'週次CSVを登録すると、このシーズンの推移が表示されます。')+
 `<div class="cards">${stat('名簿登録',ms.length+' 名',state.seasons[season].name)}${stat('今週戦功 合計',N(sumMetric(rows,'meritWeek')),last?.date||'記録なし')}${stat('今週活躍度 合計',N(sumMetric(rows,'activityWeek')),last?.date||'記録なし')}${stat('蓄積した週次記録',snaps.length+' 週','同じ週は1件として管理')}</div>`+
 (!Object.keys(state.members).length?notice('まだ名簿が登録されていません。「保存と設定」から private/initial-data.json を初期登録してください。'):'')+
 `<div class="split"><section class="panel"><h2>一門の戦功推移</h2>${chart(snaps.slice(-12).map(x=>({date:x.date,value:sumMetric(x.rows,'meritWeek')})),'今週戦功の合計')}<p class="unitnote">各週のCSVに含まれる人数で集計します。</p></section><section class="panel"><h2>隊別の今週戦功・活躍度</h2>${last?`<div class="tablewrap"><table><thead><tr><th>隊</th><th>記録人数</th><th>戦功</th><th>活躍度</th></tr></thead><tbody>${latest.map(t=>`<tr><td>${teamTitle(t.id,t.name)}</td><td>${t.stats.rows.length}</td><td class="numeric">${N(t.stats.merit.total)}</td><td class="numeric">${N(t.stats.activity.total)}</td></tr>`).join('')}${rowsUnknown.length?`<tr><td>未設定</td><td>${rowsUnknown.length}</td><td class="numeric">${N(sumMetric(rowsUnknown,'meritWeek'))}</td><td class="numeric">${N(sumMetric(rowsUnknown,'activityWeek'))}</td></tr>`:''}</tbody></table></div>`:'<div class="empty">週次記録を登録すると集計します。</div>'}</section></div>`+
 `<section class="panel"><h2>5隊の週次推移を比較</h2><div class="split"><div><h3>戦功</h3>${teamComparisonChart(series.map(x=>({...x,series:x.series.slice(-12)})),'merit')}</div><div><h3>活躍度</h3>${teamComparisonChart(series.map(x=>({...x,series:x.series.slice(-12)})),'activity')}</div></div><p class="unitnote">週の取得日時点の所属隊に集計。記録のない隊員は平均・合計の対象に含めません。</p></section>`+
 (snaps.length?`<section class="panel"><h2>週次記録一覧</h2>${snapshotTable(snaps)}</section>`:'');}
function membersInSeason(){return C.membersIn(state,season);}
function isMobileRoster(){return typeof window.matchMedia==='function'?window.matchMedia('(max-width: 680px)').matches:(typeof window.innerWidth==='number'&&window.innerWidth<=680);}
function columnStorageKey(){return 'clan-ledger-roster-columns-v2-'+(isMobileRoster()?'mobile':'desktop')+'-'+season;}
function previousColumnStorageKey(){return 'clan-ledger-roster-columns-v1-'+(isMobileRoster()?'mobile':'desktop');}
function visibleRosterColumns(){
 if(memberColumns===null){let saved=null;try{const fresh=localStorage.getItem(columnStorageKey());const old=season===state.meta.activeSeasonId?localStorage.getItem(previousColumnStorageKey()):null;saved=JSON.parse(fresh??old);}catch{}memberColumns=normalizeColumns(saved,isMobileRoster(),C.checksFor(state,season));}
 // A renamed/deleted progress item must not leave stale or invisible columns.
 memberColumns=normalizeColumns(memberColumns,isMobileRoster(),C.checksFor(state,season));
 checkFilters=filtersForColumns(memberColumns,{checkFilters}).checkFilters;
 return memberColumns;
}
function applyRosterColumns(cols){
 memberColumns=normalizeColumns(cols,isMobileRoster(),C.checksFor(state,season));
 const cleared=filtersForColumns(memberColumns,{roleFilter,teamFilter,presenceFilter,groupFilter,checkFilters});
 ({roleFilter,teamFilter,presenceFilter,groupFilter,checkFilters}=cleared);
 if(!sortKeysForColumns(memberColumns,C.checksFor(state,season)).some(([key])=>key===sortKey)) {sortKey=memberColumns.includes('role')?'rankName':'name';sortDescending=false;}
 listPage=0;
 try{localStorage.setItem(columnStorageKey(),JSON.stringify(memberColumns));}catch{}
}
function filterActiveCount(){return Number(Boolean(query.trim()))+Number(Boolean(teamFilter))+Number(roleFilter!=='all')+Number(Boolean(groupFilter))+Number(Boolean(presenceFilter))+Object.keys(checkFilters).length;}
function rosterColumnValue(id,{m,v,team}){
 const progressId=columnCheckId(id);
 if(progressId!==null){
  const val=m.checks?.[season]?.[progressId];
  const label=C.checkCompleted(val)?'完了':val==='対象外'?'対象外':'未入力';
  return `<td class="roster-cell-check"><span class="progress-state ${label==='完了'?'done':label==='対象外'?'excluded':'pending'}" title="${E(label)}">${label==='完了'?'✓':label==='対象外'?'対象外':'—'}</span></td>`;
 }
 const cells={
  name:()=>`${button(m.name,'detail',`data-id="${E(m.id)}"`,'link')}<br><small>${E(m.discordName||'—')}</small>`,
  role:()=>E(m.leadership||'一般'),
  presence:()=>presenceBadge(m),
  team:()=>`<span class="tag">${E(C.teamLabel(state,season,team))}</span><br><small>${E(m.teamPositions?.[season]||'一般')}</small>`,
  group:()=>E(m.group||'—'),
  meritWeek:()=>N(v.current?.meritWeek),
  meritTotal:()=>N(v.current?.meritTotal),
  meritPrevious:()=>N(v.previous?.meritWeek),
  delta:()=>`${v.delta>0?'+':''}${N(v.delta)}`,
  activityWeek:()=>N(v.current?.activityWeek),
  region:()=>E(v.current?.region||'—')
 };
 const numeric=['meritWeek','meritTotal','meritPrevious','delta','activityWeek'].includes(id);
 return `<td class="${numeric?'numeric ':''}roster-cell-${id} ${id==='delta'&&v.delta<0?'negative':''}">${cells[id]()}</td>`;
}
function membersView(){
 const cols=visibleRosterColumns(),checks=C.checksFor(state,season),sortOpts=sortKeysForColumns(cols,checks);
 if(!sortOpts.some(([k])=>k===sortKey)){sortKey=cols.includes('role')?'rankName':'name';sortDescending=false;}
 const show=id=>cols.includes(id),filterFields=[];
 if(show('team'))filterFields.push(`<label>隊<select id="team-filter">${options([['','すべての隊'],...C.teamDefs(state,season).map(t=>[t.id,t.name]),['__none','隊未設定']],teamFilter)}</select></label>`);
 if(show('role'))filterFields.push(`<label>一門役職<select id="role-filter">${options([['all','全員'],['officers','幹部（本部＋幹部）'],['general','一般のみ']],roleFilter)}</select></label>`);
 if(show('group'))filterFields.push(`<label>グループ<select id="group-filter">${options([['','すべてのグループ'],...groupNames().map(x=>[x,x]),['__none','グループ未設定']],groupFilter)}</select></label>`);
 if(show('presence'))filterFields.push(`<label>在籍状態<select id="presence-filter">${options([['','全在籍状態'],['在籍','在籍'],['一時離脱','一時離脱'],['一時キック','一時キック'],['離脱','離脱']],presenceFilter)}</select></label>`);
 for(const check of checks){if(show(checkColumnId(check.id)))filterFields.push(`<label>${E(check.name)}<select class="roster-check-filter" data-check-id="${E(check.id)}" aria-label="${E(check.name)}の絞り込み">${options([['all','すべて'],['incomplete','未完了'],['complete','完了'],['none','未入力'],['excluded','対象外']],checkFilters[check.id]||'all')}</select></label>`);}
 return header('メンバー名簿','表示項目を選んで、必要な人・情報だけを確認できます。',button('表示項目','member-columns','','roster-columns-button'))+
 `<div class="roster-toolbar"><label class="roster-search"><span>名前・Discord等で検索</span><input id="member-search" type="search" placeholder="名前、旧名、Discord…" aria-label="人物検索" value="${E(query)}"></label>`+
 `<details id="member-filter-panel" class="roster-filter-panel" ${isMobileRoster()?'':'open'}><summary>絞り込み <span id="filter-active-indicator" class="roster-filter-count"></span></summary><div class="roster-filter-content">${filterFields.length?`<div class="roster-filter-grid">${filterFields.join('')}</div>`:'<p class="unitnote">現在の表示項目に絞り込み条件はありません。</p>'}<div class="roster-filter-actions">${button('絞り込みを解除','reset-member-filters','','roster-reset')}</div></div></details>`+
 `<section class="roster-sort-panel" aria-label="並び替え"><label for="member-sort">並び替え</label><select id="member-sort">${options(sortOpts,sortKey)}</select>${button(sortDescending?'降順 ↓':'昇順 ↑','member-sort-direction',`aria-label="並び順を${sortDescending?'昇順':'降順'}に変更"`,'roster-sort-dir')}</section></div>`+
 `<p class="subline roster-list-count" id="member-count"></p><div class="tablewrap roster-tablewrap"><table class="roster-table"><thead><tr id="member-table-head">${rosterColumns(checks).filter(c=>show(c.id)).map(c=>`<th scope="col">${E(c.label)}</th>`).join('')}</tr></thead><tbody id="member-rows"></tbody></table></div><div class="pagination" id="member-pagination"></div><p class="unitnote">表示項目はPC・スマホそれぞれのブラウザで記憶します。非表示の項目による絞り込み・ソートは自動解除します。</p>`;
}
function rosterSortValue(entry,key){const {m,v,team}=entry;
 if(key==='team')return C.teamLabel(state,season,team);
 if(key==='group')return m.group||'';
 if(key==='presence')return C.presenceStatus(m,season);
 if(key==='region')return v.current?.region||'';
 const checkId=columnCheckId(key);
 if(checkId!==null){const value=m.checks?.[season]?.[checkId];return C.checkCompleted(value)?1:value==='対象外'?2:0;}
 if(key==='meritPrevious')return v.previous?.meritWeek;
 if(key==='delta')return v.delta;
 return v.current?.[key]??null;
}
function compareRosterEntries(a,b){
 const dir=sortDescending?-1:1;
 if(teamFilter&&teamFilter!=='__none'){
  const pos=C.positionRank(a.m,season)-C.positionRank(b.m,season);
  if(pos)return pos;
 }
 if(sortKey==='rankName'){
  const ra=C.memberRank(a.m)-C.memberRank(b.m);
  return ra||dir*a.m.name.localeCompare(b.m.name,'ja');
 }
 if(sortKey==='name')return dir*a.m.name.localeCompare(b.m.name,'ja');
 const av=rosterSortValue(a,sortKey),bv=rosterSortValue(b,sortKey);
 // Missing values always go last in both directions; unrecorded is not zero.
 if(av==null||av==='')return bv==null||bv===''?a.m.name.localeCompare(b.m.name,'ja'):1;
 if(bv==null||bv==='')return -1;
 const result=typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv),'ja');
 return dir*result||a.m.name.localeCompare(b.m.name,'ja');
}
function groupNames(){return [...new Set([...(state.groupNames||[]),...Object.values(state.members).map(m=>m.group).filter(Boolean)])].sort((a,b)=>a.localeCompare(b,'ja'));}
function presenceBadge(m){const status=C.presenceStatus(m,season);return status==='在籍'?'<span class="tag">在籍</span>':`<span class="tag ${C.TEMP_STATUSES.includes(status)?'warn':''}" title="${E(C.presenceEvent(m,season)?.note||'')}">${E(status)}</span>`;}
function teamNames(){return C.teamDefs(state,season).map(t=>t.name);}
function currentTeam(m){return C.teamId(state,season,C.teamAt(m,season));}
function renderMemberRows(){
 const cols=visibleRosterColumns();
 let list=membersInSeason().map(m=>({m,v:C.metrics(state,m.id,season),team:currentTeam(m)}));
 const q=query.trim().toLocaleLowerCase();
 list=list.filter(({m,team})=>(!q||[m.name,m.discordName,m.discordId,...m.nameHistory.map(x=>x.name),...Object.values(state.aliases).filter(a=>a.memberId===m.id).map(a=>a.name)].join(' ').toLocaleLowerCase().includes(q))
 &&(!cols.includes('team')||!teamFilter||(teamFilter==='__none'?!team:team===teamFilter))
 &&(!cols.includes('role')||roleFilter==='all'||(roleFilter==='officers'?C.memberRank(m)<2:C.memberRank(m)===2))
 &&(!cols.includes('presence')||!presenceFilter||C.presenceStatus(m,season)===presenceFilter)
 &&(!cols.includes('group')||!groupFilter||(groupFilter==='__none'?!m.group:m.group===groupFilter))
 &&Object.entries(checkFilters).every(([id,status])=>!cols.includes(checkColumnId(id))||checkFilterMatches(m.checks?.[season]?.[id],status,C.checkCompleted(m.checks?.[season]?.[id]))));
 list.sort(compareRosterEntries);
 const pages=Math.max(1,Math.ceil(list.length/50));listPage=Math.max(0,Math.min(listPage,pages-1));
 $('#member-count').textContent=`${list.length} 名を表示 · ${C.orderedSnapshots(state,season).at(-1)?.date||'週次記録なし'} · ${cols.length}列表示`;
 const badge=$('#filter-active-indicator');if(badge)badge.textContent=filterActiveCount()?`（${filterActiveCount()}条件を適用中）`:'（条件なし）';
 $('#member-rows').innerHTML=list.slice(listPage*50,listPage*50+50).map(entry=>`<tr>${cols.map(id=>rosterColumnValue(id,entry)).join('')}</tr>`).join('')||`<tr><td colspan="${cols.length}">該当する人物はいません。</td></tr>`;
 $('#member-pagination').innerHTML=button('前へ','member-prev',listPage===0?'disabled':'')+`<span>${listPage+1} / ${pages}</span>`+button('次へ','member-next',listPage>=pages-1?'disabled':'');
}
async function editMemberColumns(){
 const cols=visibleRosterColumns();
 const allColumns=rosterColumns(C.checksFor(state,season));
 const choice=c=>`<label class="roster-column-choice"><input type="checkbox" name="col_${E(c.id)}" value="1" ${cols.includes(c.id)?'checked':''} ${c.id==='name'?'disabled':''}>${E(c.label)}${c.id==='name'?'（固定）':''}</label>`;
 const base=allColumns.filter(c=>!c.isCheck),progress=allColumns.filter(c=>c.isCheck);
 const body=`<p class="subline">名簿に表示する列を選んでください。ゲーム内名前は常に表示します。設定はこのブラウザの${isMobileRoster()?'スマホ':'PC'}表示とシーズンにだけ保存されます。</p><h3>基本項目</h3><div class="roster-column-choices">${base.map(choice).join('')}</div><h3>シーズン進捗 · ${E(state.seasons[season].name)}</h3><p class="unitnote">各チェック項目を個別の列として表示できます。</p><div class="roster-column-choices">${progress.map(choice).join('')||'<p class="unitnote">進捗項目がありません。</p>'}</div><p class="unitnote">非表示にした列の絞り込み条件・ソート指定は自動的に解除されます。</p>`;
 const d=await modalForm('表示項目を選ぶ',body,'表示を更新');if(!d)return;
 applyRosterColumns(['name',...allColumns.filter(c=>c.id!=='name'&&d['col_'+c.id]).map(c=>c.id)]);
 render();
}
function memberForm(m){const check=m.checks?.[season]||{},defs=C.checksFor(state,season);return `<form id="member-form" class="formgrid" data-id="${m.id}">${[['name','ゲーム内名前'],['discordName','Discord名前'],['discordId','Discord ID（原文）'],['role','役割（原文）'],['origin','元所属'],['joinHistory','加入経緯']].map(([k,l])=>`<label>${l}<input name="${k}" value="${E(m[k])}" ${k==='name'?'required':''} maxlength="500"></label>`).join('')}<label>一門内役職<select name="leadership">${options([['一般','一般'],['幹部','幹部'],['本部','本部']],m.leadership||'一般')}</select></label><div class="full unitnote">所属グループ：${E(m.group||'未設定')}（変更は「保存と設定」からExcel一括インポート）</div><label class="full">ざっくり元所属とか経緯（原文）<textarea name="originContext">${E(m.originContext)}</textarea></label><label class="full">自由記述メモ<textarea name="note">${E(m.note)}</textarea></label><div class="full"><h3>シーズン進捗 · ${E(state.seasons[season].name)}</h3><p class="unitnote">項目は管理・記録の「名簿・分隊の管理」から追加・変更できます。未入力／完了／対象外を選べます。</p></div>${defs.map(x=>`<label>${E(x.name)}<select name="check_${E(x.id)}">${options([['','未入力'],['○','完了'],['対象外','対象外']],C.checkCompleted(check[x.id])?'○':check[x.id]==='対象外'?'対象外':'')}</select></label>`).join('')}<label>現在の隊<select name="team">${options([['','未設定'],...C.teamDefs(state,season).map(t=>[t.id,t.name])],currentTeam(m))}</select></label><label>隊内役職<select name="teamPosition">${options([['一般','一般'],['副隊長','副隊長'],['隊長','隊長']],m.teamPositions?.[season]||'一般')}</select></label><label>変更日<input name="date" type="date" required value="${C.today()}"></label><label>所属状態<select name="status">${options(['在籍','一時離脱','一時キック','離脱','休止','過去在籍'].map(x=>[x,x]),C.presenceStatus(m,season))}</select></label><label>隊変更メモ<input name="teamNote" placeholder="隊を変更する理由"></label><label>在籍状態の理由（任意）<input name="presenceNote" maxlength="2000" placeholder="友好一門へ移動 / 捕虜化など"></label><div class="full actions"><button type="submit" class="primary" ${demo?'disabled':''}>変更を共有DBへ保存</button><span class="muted">CSV取込では、この入力欄は上書きされません。</span></div></form>`;}
function detail(){const m=state.members[detailId];if(!m){detailId='';return membersView();}const v=C.metrics(state,m.id,season),hist=C.history(state,m.id,season),legacy=Object.values(state.legacy).filter(r=>r.memberId===m.id),contrib=Object.values(state.contributions).filter(r=>r.memberId===m.id);
 return button('← 名簿に戻る','back','','back')+header(m.name,`内部ID：${m.id}`,button('この人物の変更履歴','person-audit',`data-id="${m.id}"`))+
 `<div class="cards">${stat('今週戦功',N(v.current?.meritWeek),v.date||'記録なし')}${stat('総戦功',N(v.current?.meritTotal),'表示シーズン内')}${stat('前週差',(v.delta>0?'+':'')+N(v.delta),'前週：'+N(v.previous?.meritWeek))}${stat('今週活躍度',N(v.current?.activityWeek),v.current?.region||'記録なし')}</div>`+
 `<div class="split"><section class="panel"><h2>戦功の推移</h2>${chart(hist.map(x=>({date:x.snapshot.date,value:x.row?.meritWeek??null})),'戦功今週')}</section><section class="panel"><h2>活躍度の推移</h2>${chart(hist.map(x=>({date:x.snapshot.date,value:x.row?.activityWeek??null})),'活躍度今週','#a07a46')}</section></div>`+
 `<section class="panel"><div class="row" style="justify-content:space-between;align-items:center"><h2>人物・運営情報</h2>${presenceBadge(m)} ${C.TEMP_STATUSES.includes(C.presenceStatus(m,season))?button('在籍に戻す','return-member',`data-id="${m.id}"`):''}</div>${memberForm(m)}<h3>一時離脱・復帰の履歴</h3>${(m.presenceEvents||[]).filter(x=>x.seasonId===season).toReversed().map(x=>`<p class="presence-event"><strong>${E(x.status)}</strong> · ${E(x.date)} · ${x.source==='csv'?'CSV検出':'手動'}<br><small>${E(x.note||'理由未記入')}</small></p>`).join('')||'<p class="unitnote">状態変更の履歴はまだありません。</p>'}</section><section class="panel"><h2>週次履歴</h2>${hist.length?`<div class="tablewrap"><table><thead><tr><th>取得日</th><th>戦功今週</th><th>戦功総量</th><th>活躍度今週</th><th>活躍度総量</th><th>威信</th><th>所属地方</th><th>ゲーム内グループ</th></tr></thead><tbody>${hist.toReversed().map(({snapshot:x,row:r})=>`<tr><td>${E(x.date)}</td>${['meritWeek','meritTotal','activityWeek','activityTotal','prestige'].map(k=>`<td class="numeric">${N(r?.[k])}</td>`).join('')}<td>${E(r?.region||'—')}</td><td>${E(r?.gameGroup||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">このシーズンの週次記録はまだありません。</div>'}</section>`+
 `<section class="panel"><h2>過去実績・移行した元資料</h2><p class="subline">S4戦功・S3戦功・S3貢献値は元資料の「万」単位。Sheet1の戦功は単位・時点未確認の参考値です。</p>${legacy.length?legacy.map(r=>`<details class="details"><summary>${E(r.sheet)} · ${E(r.sourceName)} · ${E(r.group)} <small>行${r.row} / ${E(r.match)}</small></summary>${Object.entries(r.values).map(([k,val])=>`<div class="sourcevalue"><small>${E(k)}</small><span>${E(val)}</span></div>`).join('')}<p class="unitnote">${E(r.file)} / ${E(r.reviewNote)}</p>${button('照合を訂正','review-record',`data-id="${r.id}"`)}</details>`).join(''):'<p class="subline">紐付いた過去資料はありません。移行・照合確認で旧名の資料を紐付けられます。</p>'}</section>`+
 `<div class="split"><section class="panel"><h2>隊・所属履歴</h2><div class="timeline">${[...m.teamHistory].sort((a,b)=>b.date.localeCompare(a.date)).map(t=>`<div><small>${E(t.date)}〜 · ${E(state.seasons[t.seasonId]?.name)}</small><strong>${E(t.team||'未設定')}</strong><p class="muted">${E(t.note)}</p>${button('訂正','correct-team',`data-id="${m.id}" data-history="${t.id}"`)}</div>`).join('')||'<p>隊履歴なし</p>'}</div><details class="details"><summary>シーズン所属</summary>${m.memberships.map(x=>`<p>${E(state.seasons[x.seasonId]?.name)} / ${E(x.status)} / ${E(x.since||'日付未確認')}<br><small>${E(x.note)}</small></p>`).join('')}</details></section><section class="panel"><h2>名前の履歴</h2>${m.nameHistory.map(x=>`<p>${E(x.date)} · ${E(x.name)}</p>`).join('')}<details class="details"><summary>照合に使う旧名・別名</summary>${Object.values(state.aliases).filter(x=>x.memberId===m.id).map(x=>`<p>${E(x.name)} <small>${E(x.source)}</small> ${button('紐付け訂正','correct-alias',`data-id="${x.id}"`)}</p>`).join('')}</details><hr><h2>貢献の記録</h2>${contrib.map(x=>`<p>${E(x.date)} · ${E(x.category)}<br><small>${E(x.note)}</small></p>`).join('')||'<p class="muted">記録はまだありません。</p>'}${button('事実を記録','add-contribution',`data-id="${m.id}"`)}</section></div><section class="panel"><h2>変更履歴</h2><p class="subline">操作者・変更前後を、この人物で絞って表示します。</p>${button('変更履歴を表示','person-audit',`data-id="${m.id}"`)}</section>`;}
function snapshotTable(xs){return `<div class="tablewrap"><table><thead><tr><th>取得日</th><th>人数</th><th>戦功今週 合計</th><th>活躍度今週 合計</th><th>元ファイル</th><th>訂正履歴</th><th></th></tr></thead><tbody>${[...xs].reverse().map(x=>`<tr><td>${E(x.date)}</td><td>${x.rows.length}</td><td class="numeric">${N(sumMetric(x.rows,'meritWeek'))}</td><td class="numeric">${N(sumMetric(x.rows,'activityWeek'))}</td><td>${E(x.fileName)}</td><td>${x.versions.length} 回</td><td>${button('内容','snapshot',`data-id="${x.id}"`)}</td></tr>`).join('')}</tbody></table></div>`;}
function importView(){return header('週次CSV取込','選択 → 照合を確認 → 週次記録として共有DBへ登録。')+`<section class="panel"><form id="csv-form" class="formgrid"><label>ゲームの一門集計CSV<input id="csv-file" type="file" accept=".csv,text/csv" ${demo?'disabled':''}></label><label>取得日<input id="csv-date" type="date" value="${E(importData?.date||C.today())}" required></label></form><p class="unitnote">表示シーズン：${E(state.seasons[season].name)}。添付サンプルは2026-08-16のS4資料です。取り込むときはPK1 / S4へ切り替えてください。</p></section>${importData?`<section class="panel"><h2>照合結果 · ${E(importData.fileName)}</h2><p id="import-count" class="subline"></p><p class="unitnote">${E(importData.encoding)} · 同名の候補が複数ある場合も、選択するまでは未紐付けです。現在のゲーム名はCSVで変更しません。</p><div class="row" style="margin:15px 0"><label class="checkline"><input type="checkbox" id="only-unmatched" checked>未紐付けだけ表示</label><input id="import-search" placeholder="CSV内の名前で検索" style="max-width:260px" aria-label="CSV内検索"></div><div class="tablewrap"><table><thead><tr><th>CSVの名前</th><th>今週戦功</th><th>紐付け先</th><th>状態</th></tr></thead><tbody id="import-rows"></tbody></table></div><div class="actions" style="margin-top:20px">${button('確認した内容を登録','commit-csv','','primary')}${button('取込を取り消す','cancel-csv')}</div></section>`:''}<section class="panel"><h2>保存済みのCSV履歴</h2>${snapshotTable(C.orderedSnapshots(state,season))}</section>`;}
function renderImportRows(){if(!$('#import-rows'))return;const only=$('#only-unmatched').checked,q=$('#import-search').value.toLowerCase(),missing=importRows.filter(r=>!r.memberId&&!r.create).length;$('#import-count').textContent=`全${importRows.length}件 / 未紐付け${missing}件 / 新規予定${importRows.filter(r=>r.create).length}件 / 自動復帰予定${importData&&C.validDate(importData.date)?C.autoReturnCandidates(state,season,importData.date,importRows).length:0}名${importData.blankNumbers?' / 数値空欄あり（欠測として保存）':''}`;
 $('#import-rows').innerHTML=importRows.map((r,i)=>({r,i})).filter(({r})=>(!only||(!r.memberId&&!r.create))&&r.name.toLowerCase().includes(q)).map(({r,i})=>`<tr><td>${E(r.name)}</td><td class="numeric">${N(r.meritWeek)}</td><td><select class="import-select" data-import-row="${i}" aria-label="${E(r.name)}の紐付け">${memberOptions(r.memberId)}<option value="__new" ${r.create?'selected':''}>＋ 新規人物として登録</option></select></td><td><span class="tag ${!r.memberId&&!r.create?'warn':''}">${r.create?'新規登録予定':r.memberId?'紐付け済み':'未紐付け'}</span></td></tr>`).join('')||'<tr><td colspan="4">該当する行はありません。「未紐付けだけ表示」を外すと全件を確認できます。</td></tr>';
 $('[data-action="commit-csv"]').disabled=missing>0||demo;}
function teamsView(){const ms=membersInSeason(),defs=C.teamDefs(state,season),last=C.orderedSnapshots(state,season).at(-1),groups=defs.map(t=>({...t,list:ms.filter(m=>currentTeam(m)===t.id)}));
 groups.push({id:'',name:'未設定',list:ms.filter(m=>!defs.some(t=>t.id===currentTeam(m)))});
 return header('分隊名簿','所属メンバーと隊長・副隊長の早見表。各隊の今週の様子から詳しい記録を確認できます。')+
 `<div class="split squad-grid">${groups.map(g=>{const list=[...g.list].sort((a,b)=>C.positionRank(a,season)-C.positionRank(b,season)||a.name.localeCompare(b.name,'ja'));
 const captains=list.filter(m=>C.positionRank(m,season)===0),deputies=list.filter(m=>C.positionRank(m,season)===1),regular=list.filter(m=>C.positionRank(m,season)===2),regularGroups=C.squadGeneralGroups(regular),stats=C.teamStats(state,season,g.id,last),showName=m=>`${button(m.name,'detail',`data-id="${m.id}"`,'link')}${C.TEMP_STATUSES.includes(C.presenceStatus(m,season))?` <span class="tag warn">${E(C.presenceStatus(m,season))}</span>`:''}`;
 return `<section class="panel squad-card"><div class="row squad-head"><h2>${teamTitle(g.id,g.name)}</h2><span class="tag">${list.length}名</span></div>${g.id?`<div class="squad-summary"><div><small>今週戦功</small><strong>${N(stats.merit.total)}</strong></div><div><small>今週活躍度</small><strong>${N(stats.activity.total)}</strong></div></div><div class="squad-actions">${button('隊の記録を見る →','team-record',`data-id="${g.id}"`)}</div>`:''}
 <div class="squad-role"><small>隊長</small><div class="squad-names">${captains.map(showName).join('')||'<span class="muted">未任命</span>'}</div></div>
 <div class="squad-role"><small>副隊長</small><div class="squad-names">${deputies.map(showName).join('')||'<span class="muted">未任命</span>'}</div></div>
 <div class="squad-role"><small>一般隊員</small><div class="squad-clusters">${regularGroups.map(cluster=>`<div class="squad-cluster" role="group" aria-label="${['本部','幹部','一般'][cluster.rank]}・同じグループの隊員">${cluster.members.map(m=>`<span class="squad-person">${showName(m)}${C.memberRank(m)<2?`<span class="squad-leadership">${E(m.leadership)}</span>`:''}</span>`).join('')}</div>`).join('')||'<span class="muted">該当者なし</span>'}</div></div></section>`;}).join('')}</div>`;
}
function teamRecordView(){const t=C.teamDefs(state,season).find(x=>x.id===teamDetailId);if(!t){teamDetailId='';return teamsView();}
 const series=C.teamSeries(state,season,t.id),cur=series.at(-1),prev=series.length>=2&&Date.parse(C.weekKey(series.at(-1).date))-Date.parse(C.weekKey(series.at(-2).date))===7*86400000?series.at(-2):null,members=membersInSeason().filter(m=>currentTeam(m)===t.id).sort((a,b)=>C.positionRank(a,season)-C.positionRank(b,season)||a.name.localeCompare(b.name,'ja'));
 const col=E(C.teamColor(t.id).hex),metric=(key,label)=>chart(series.slice(-12).map(x=>({date:x.date,value:metricValue(x,key)})),label,col);
 return button('← 分隊名簿に戻る','back-team','','back')+header(t.name+' の記録','自隊の戦功・活躍度を確認します。他隊との比較は「一門のようす」で確認できます。').replace('<h1>','<h1>'+teamMarker(t.id)+' ')+
 `<div class="cards">${stat('今週戦功',N(cur?.merit.total),percentChange(cur?.merit.total,prev?.merit.total))}${stat('1人あたり戦功',cur?.merit.average==null?'—':N(Math.round(cur.merit.average)),`記録あり ${cur?.merit.count||0}名`)}${stat('今週活躍度',N(cur?.activity.total),percentChange(cur?.activity.total,prev?.activity.total))}${stat('1人あたり活躍度',cur?.activity.average==null?'—':N(Math.round(cur.activity.average)),`記録あり ${cur?.activity.count||0}名`)}</div>`+
 `<div class="split"><section class="panel"><h2>${teamTitle(t.id,t.name)} · 戦功推移</h2>${metric('merit','今週戦功')}</section><section class="panel"><h2>活躍度推移</h2>${metric('activity','今週活躍度')}</section></div>`+
 `<section class="panel"><h2>隊員の今週の記録</h2><p class="unitnote">${cur?.date?E(cur.date)+'のCSV':'週次CSV未登録'}。未収録のメンバーは「未記録」であり、0ではありません。</p><div class="tablewrap"><table><thead><tr><th>メンバー</th><th>隊役職</th><th>在籍状態</th><th>戦功</th><th>活躍度</th></tr></thead><tbody>${members.map(m=>{const r=cur?.rows.find(r=>r.memberId===m.id);return `<tr><td>${button(m.name,'detail',`data-id="${m.id}"`,'link')}</td><td>${E(m.teamPositions?.[season]||'一般')}</td><td>${presenceBadge(m)}</td><td class="numeric">${N(r?.meritWeek)}</td><td class="numeric">${N(r?.activityWeek)}</td></tr>`;}).join('')||'<tr><td colspan="5">メンバーがいません。</td></tr>'}</tbody></table></div></section>`+
 `<section class="panel"><h2>週ごとの実績</h2><div class="tablewrap"><table><thead><tr><th>取得日</th><th>記録人数</th><th>戦功</th><th>戦功平均</th><th>活躍度</th><th>活躍度平均</th></tr></thead><tbody>${[...series].reverse().map(x=>`<tr><td>${E(x.date)}</td><td>${x.rows.length}名</td><td class="numeric">${N(x.merit.total)}</td><td class="numeric">${N(x.merit.average==null?null:Math.round(x.merit.average))}</td><td class="numeric">${N(x.activity.total)}</td><td class="numeric">${N(x.activity.average==null?null:Math.round(x.activity.average))}</td></tr>`).join('')||'<tr><td colspan="6">週次記録がありません。</td></tr>'}</tbody></table></div><p class="unitnote">各週の取得日時点の隊所属を基準に集計。後から隊を移動しても過去の実績は移動しません。</p></section>`;
}
function managementView(){return header('名簿・分隊の管理','運営担当者向けの設定・名簿出力。普段の確認は「メンバー名簿」「分隊名簿」を利用してください。')+
 `<section class="panel"><h2>メンバーの追加</h2><p>新しいゲームアカウントを名簿に登録します。</p>${button('メンバーを追加','add-member','','primary')}</section>`+
 `<section class="panel"><h2>分隊の設定・編成</h2><div class="actions">${button('隊名を編集','edit-teams')}${button('編成を記録','new-formation')}</div><p class="unitnote">隊の一括再編が必要な場合のみ「編成を記録」を使用します。隊所属を一括変更し、日付と変更理由を履歴に残す機能です。</p><details class="details"><summary>過去の編成記録</summary>${Object.values(state.formations).filter(f=>f.seasonId===season).sort((a,b)=>b.start.localeCompare(a.start)).map(f=>`<p><strong>${E(f.start)}〜 ${E(f.name)}</strong><br>${E(f.note)}</p>`).join('')||'記録はありません'}</details></section>`+
 `<section class="panel"><h2>進捗項目の設定</h2><p>Discord加入・出生済など、シーズン単位のチェック項目を管理します。</p>${button('進捗項目を管理','edit-checks')}</section>`+
 `<section class="panel"><h2>隊分け表を出力</h2><div class="actions">${button('隊分け表 Excel','export','data-format="team"')}${button('隊分け表 CSV','team-csv')}</div></section>`;}
function reviewView(){return header('移行・照合確認','出典を見比べ、同一アカウントと確認できたものを紐付けます。')+notice('Discord IDの共有だけでは統合しません。S4の通常／補給の凸は別々に保持しています。')+`<section class="panel"><div class="filters"><input id="review-search" placeholder="資料にある名前を検索" value="${E(reviewQuery)}" aria-label="移行資料検索"><select id="review-filter">${options([['pending','未紐付け'],['all','すべての元資料']],reviewFilter)}</select></div><div id="review-rows"></div></section><section class="panel"><h2>原資料の要確認事項</h2>${Object.values(state.issues).map(i=>`<div class="audititem"><div class="row"><span class="tag ${i.status==='open'?'warn':''}">${i.status==='open'?'要確認':'確認済み'}</span><strong>${E(i.kind)}</strong></div><p>${E(i.description)}</p>${i.note?`<p class="muted">${E(i.note)}</p>`:''}${button(i.status==='open'?'確認内容を記録':'記録を更新','resolve-issue',`data-id="${i.id}"`)}</div>`).join('')}</section>`;}
function renderReviewRows(){const data=Object.values(state.legacy).filter(r=>(reviewFilter==='all'||!r.memberId)&&r.sourceName.toLowerCase().includes(reviewQuery.toLowerCase())),groups=new Map();for(const r of data){if(!groups.has(r.sourceName))groups.set(r.sourceName,[]);groups.get(r.sourceName).push(r);}$('#review-rows').innerHTML=`<p class="subline">${groups.size} 名前 / ${data.length} 件</p>`+[...groups].map(([name,rs])=>`<details class="details"><summary>${E(name)} <span class="tag ${rs.some(r=>!r.memberId)?'warn':''}">${rs.some(r=>!r.memberId)?'未紐付け':E(state.members[rs[0].memberId]?.name)}</span> <small>${rs.length} 件</small></summary><div class="tablewrap"><table><thead><tr><th>シート / 行</th><th>区分</th><th>元の値</th><th>紐付け先</th><th></th></tr></thead><tbody>${rs.map(r=>`<tr><td>${E(r.sheet)} / ${r.row}</td><td>${E(r.group)}</td><td class="wrap">${E(Object.entries(r.values).map(([k,v])=>k+'：'+v).join(' / '))}</td><td>${E(state.members[r.memberId]?.name||'未紐付け')}</td><td>${button('この記録を紐付け','review-record',`data-id="${r.id}"`)}</td></tr>`).join('')}</tbody></table></div>${button('この名前の未紐付け記録をまとめて紐付け','review-name',`data-name="${E(name)}"`)}</details>`).join('')||'<div class="empty">該当する資料はありません。</div>';}
let auditMember='';
function auditView(){return header('変更履歴','共有DBが記録した操作者・日時・変更前後。過去ログは通常編集では消えません。')+`<section class="panel"><div class="row"><label>人物で絞る<select id="audit-member">${memberOptions(auditMember)}</select></label>${button('最新履歴を読む','reload-audit')}</div><div id="audit-rows">${logsLoaded?auditRows():'履歴を読み込んでいます…'}</div>${button('さらに過去を読む','more-audit',logs.length?'':'disabled')}</section>`;}
function pathLabel(path){const xs=path.split('.');if(xs[0]==='members'){return (state.members[xs[1]]?.name||xs[1])+' / '+xs.slice(2).map(x=>fieldNames[x]||x).join(' / ');}return xs.map(x=>fieldNames[x]||x).join(' / ');}
function auditRows(){const filtered=logs.filter(l=>!auditMember||l.changes.some(c=>c.path.includes(auditMember)||JSON.stringify([c.before,c.after]).includes(auditMember)));return filtered.map(l=>`<article class="audititem"><div class="audittop"><strong>${E(l.operator)}</strong><small>${E(DT(l.happened_at))}</small><span class="tag">${E(l.kind)}</span>${l.imported?'<span class="tag warn">バックアップ由来</span>':''}</div><p>${E(l.summary)}</p><details class="details"><summary>変更前・変更後（${l.changes.length}項目）</summary>${l.changes.filter(c=>!auditMember||c.path.includes(auditMember)||JSON.stringify([c.before,c.after]).includes(auditMember)).map(c=>`<p><strong>${E(pathLabel(c.path))}</strong></p><div class="auditdiff"><div><small>変更前</small><pre>${E(fmtDiff(c.before))}</pre></div><div><small>変更後</small><pre>${E(fmtDiff(c.after))}</pre></div></div>`).join('')}</details></article>`).join('')||'<div class="empty">表示対象の変更履歴はありません。</div>';}
async function loadLogs(more=false){try{if(demo){logsLoaded=true;}else{const next=await store.audit(100,more?logs.at(-1)?.seq:null);logs=more?[...logs,...next]:next;logsLoaded=true;if(more&&!next.length)toast('すべての履歴を読み込みました');}if($('#audit-rows'))$('#audit-rows').innerHTML=auditRows();const moreBtn=$('[data-action="more-audit"]');if(moreBtn)moreBtn.disabled=demo||!logs.length;}catch(e){if($('#audit-rows'))$('#audit-rows').innerHTML=notice(e.message,'error');}}
function settingsView(){return header('保存と設定','バックアップは人物情報・週次記録・元資料・変更履歴を含みます。')+
 `<section class="panel"><h2>グループ一括インポート</h2><p>Excel（.xlsx）の先頭シートに「Discord ID」「グループ」の見出しを用意してください。同じDiscord IDを持つ本アカ・サブアカすべてに同じグループを割り当てます。Discord IDはExcelで文字列として保存してください。Excelのフリガナ情報は取り込みません。旧版でグループ名に読み仮名が連結された場合も、同じExcelを再取り込みすると修正できます。</p><label>グループ割当Excel<input id="group-import-file" type="file" accept=".xlsx" ${demo?'disabled':''}></label><div id="group-import-preview">${groupImportHtml()}</div></section>`+
 `<section class="panel"><h2>バックアップ・復元</h2><p>定期的にJSONを保存してください。復元前にも、その時点のバックアップをダウンロードします。</p><div class="actions" style="margin:18px 0">${button('全データをバックアップ','backup','','primary')}</div><label>初期データ / 復元用JSON<input id="restore-file" type="file" accept=".json" ${demo?'disabled':''}></label><p class="unitnote">初回：private/initial-data.json を選択。通常運用中の復元は現在データを置き換えるため、確認画面を表示します。既存の編集履歴は残ります。</p></section>`+
 `<section class="panel"><h2>シーズン管理</h2><div class="tablewrap"><table><thead><tr><th>シーズン</th><th>開始日</th><th>終了日</th><th></th></tr></thead><tbody>${Object.values(state.seasons).map(s=>`<tr><td>${E(s.name)}</td><td>${E(s.start||'未設定')}</td><td>${E(s.end||'未設定')}</td><td>${button('編集','edit-season',`data-id="${s.id}"`)}</td></tr>`).join('')}</tbody></table></div><div class="actions" style="margin-top:15px">${button('新しいシーズン','new-season')}${button('表示中を既定シーズンにする','default-season')}</div></section>`+
 `<section class="panel"><h2>保存の状態</h2><p>${demo?'読取専用プレビュー':`共有DB / revision ${revision} / 最終更新 ${E(DT(updatedAt))}`}</p><p class="subline">通常のアプリ更新ではDBを作り直しません。接続先は公開ファイルのconfig.jsで管理します。</p><details class="details"><summary>端末に保持するもの</summary><p>接続先と公開用キーは公開ファイルで共通設定。合言葉は保存せず、利用トークンと操作者名はタブのセッション内のみ（最長12時間）。人物データの正本は共有DBです。</p></details></section>`;}

document.addEventListener('input',e=>{const t=e.target;if(t.id==='member-search'){query=t.value;listPage=0;renderMemberRows();}else if(t.id==='review-search'){reviewQuery=t.value;renderReviewRows();}else if(t.id==='import-search'){renderImportRows();}else if(t.closest('#member-form'))dirty=true;});
document.addEventListener('change',async e=>{try{const t=e.target;
 if(t.id==='season-select'){if((dirty||importRows.length)&&!confirm('編集中の内容を閉じてシーズンを切り替えますか？')){t.value=season;return;}season=t.value;memberColumns=null;checkFilters={};dirty=false;importData=null;importRows=[];detailId='';render();}
 else if(t.id==='team-filter'){teamFilter=t.value;listPage=0;renderMemberRows();}
 else if(t.id==='member-sort'){sortKey=t.value;sortDescending=['meritWeek','meritTotal','meritPrevious','delta','activityWeek'].includes(sortKey);listPage=0;render();}
 else if(t.classList?.contains?.('roster-check-filter')){const id=t.dataset.checkId;if(C.checksFor(state,season).some(d=>d.id===id)&&visibleRosterColumns().includes(checkColumnId(id))){if(t.value==='all')delete checkFilters[id];else checkFilters[id]=t.value;listPage=0;renderMemberRows();}}
 else if(['role-filter','group-filter','presence-filter'].includes(t.id)){({'role-filter':v=>roleFilter=v,'group-filter':v=>groupFilter=v,'presence-filter':v=>presenceFilter=v}[t.id])(t.value);listPage=0;renderMemberRows();}
 else if(t.id==='review-filter'){reviewFilter=t.value;renderReviewRows();}
 else if(t.id==='audit-member'){auditMember=t.value;$('#audit-rows').innerHTML=auditRows();}
 else if(t.id==='only-unmatched')renderImportRows();
 else if(t.dataset.importRow!==undefined){const r=importRows[Number(t.dataset.importRow)];r.create=t.value==='__new';r.memberId=r.create?'':t.value;renderImportRows();}
 else if(t.id==='csv-date'){if(importData){importData.date=t.value;renderImportRows();}}
 else if(t.id==='csv-file'&&t.files[0]){const f=t.files[0];C.assert(f.size<10*1024*1024,'CSVは10MB以内にしてください');const parsed=C.decodeCSV(await f.arrayBuffer());const inferred=f.name.match(/(20\d{2})[_-](\d{2})[_-](\d{2})/);importData={...parsed,fileName:f.name,hash:await C.fingerprint(parsed.rows),date:inferred?inferred.slice(1).join('-'):$('#csv-date').value};importRows=C.previewImport(state,parsed);render();}
 else if(t.id==='group-import-file'&&t.files[0]){const f=t.files[0];C.assert(f.name.toLowerCase().endsWith('.xlsx'),'xlsxファイルを選んでください');C.assert(f.size<5*1024*1024,'Excelは5MB以内にしてください');groupImportPreview=previewGroupImport(state,await parseGroupWorkbook(await f.arrayBuffer(),window.JSZip));groupImportFile=f.name;$('#group-import-preview').innerHTML=groupImportHtml();}
 else if(t.id==='preview-file'&&t.files[0]){const b=await readBackup(t.files[0]);state=b.state;revision=b.revision||0;updatedAt=b.exportedAt;logs=[...b.audit].reverse();logsLoaded=true;demo=true;season=state.meta.activeSeasonId;page='dashboard';render();}
 else if(t.id==='restore-file'&&t.files[0]){const b=await readBackup(t.files[0]);await restore(b);t.value='';}
 }catch(e){toast(e.message,true);}});
async function readBackup(file){C.assert(file.size<50*1024*1024,'バックアップは50MB以内にしてください');return C.validateBackup(JSON.parse(await file.text()));}
document.addEventListener('submit',async e=>{if(!['login-form','member-form'].includes(e.target.id))return;e.preventDefault();try{const f=e.target,d=Object.fromEntries(new FormData(f));
 if(f.id==='login-form'){const btn=f.querySelector('button[type="submit"]');btn.disabled=true;const phrase=d.passphrase;d.passphrase='';f.elements.passphrase.value='';try{await store.login(phrase,d.operator);demo=false;state=null;dirty=false;importRows=[];importData=null;await refresh(true);season=state.meta.activeSeasonId;render();}catch(err){loginView(err.message);}}
 else{const m=state.members[f.dataset.id],patch=Object.fromEntries(['name','discordName','discordId','role','origin','joinHistory','originContext','note','leadership'].map(k=>[k,d[k]]));patch.checks=Object.fromEntries(C.checksFor(state,season).map(x=>[x.id,d['check_'+x.id]]));if(d.team&&d.teamPosition==='隊長'&&membersInSeason().some(x=>x.id!==m.id&&currentTeam(x)===d.team&&x.teamPositions?.[season]==='隊長'))throw new Error('この隊にはすでに隊長がいます。先に現在の隊長の役職を変更してください。');const next=C.editMember(state,m.id,{...patch,teamPosition:d.team?d.teamPosition:'一般'},{seasonId:season,date:d.date,team:d.team,teamNote:d.teamNote,status:d.status,presenceNote:d.presenceNote});if(await save(next,'edit',m.name+' の人物情報・所属を更新'))render();}
 }catch(e){toast(e.message,true);}});
async function navigate(p){if((dirty||importRows.length)&&p!==page&&!confirm('編集中の内容を閉じて移動しますか？'))return;if(p!==page){dirty=false;importData=null;importRows=[];}page=p;detailId='';teamDetailId='';if(p!=='settings')groupImportPreview=null;render();}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;try{if(busy){toast('保存処理中です');return;}
 if(dirty&&['person-audit','correct-team','review-record','add-contribution','correct-alias'].includes(a)){if(!confirm('人物情報の未保存の入力を閉じて操作しますか？'))return;dirty=false;}
 if(a==='nav')await navigate(b.dataset.page);
 else if(a==='team-record'){teamDetailId=b.dataset.id;render();window.scrollTo(0,0);}
 else if(a==='back-team'){teamDetailId='';render();}
 else if(a==='return-member'){await returnMember(b.dataset.id);}
 else if(a==='detail'){if(dirty&&!confirm('未保存の入力を閉じますか？'))return;dirty=false;returnFromDetail=page==='teams'?'teams':'members';page='members';detailId=b.dataset.id;render();window.scrollTo(0,0);}
 else if(a==='back'){if(dirty&&!confirm('未保存の入力を閉じますか？'))return;dirty=false;detailId='';if(returnFromDetail==='teams')page='teams';render();}
 else if(a==='refresh')await refresh(true);
 else if(a==='logout'){if(dirty&&!confirm('未保存の入力を閉じてログアウトしますか？'))return;const logoutResult=!demo?await store.logout():{serverRevoked:true};demo=false;state=null;dirty=false;importRows=[];importData=null;logs=[];logsLoaded=false;page='dashboard';loginView(logoutResult.serverRevoked?'':'この端末からログアウトしました。通信できずサーバー側の失効は未確認です。利用セッションは最長12時間で失効します。');}
 else if(a==='reconnect')await reconnect();
 else if(a==='operator'){const d=await modalForm('操作者名',`<label>表示名<input name="operator" value="${E(operator())}" required maxlength="80"></label>`);if(d){C.assert(d.operator.trim(),'名前を入力してください');if(!demo)await store.changeOperator(d.operator);else sessionStorage.setItem('clan-ledger-operator',d.operator.trim());b.textContent='操作者：'+operator();}}
 else if(a==='member-prev'||a==='member-next'){listPage+=a==='member-prev'?-1:1;renderMemberRows();}
  else if(a==='member-columns')await editMemberColumns();
  else if(a==='member-sort-direction'){sortDescending=!sortDescending;listPage=0;render();}
  else if(a==='reset-member-filters'){query='';teamFilter='';roleFilter='all';groupFilter='';checkFilters={};presenceFilter='';listPage=0;render();}
 else if(a==='commit-csv')await commitCSV();
 else if(a==='cancel-csv'){importRows=[];importData=null;render();}
 else if(a==='add-member')await addMember();
 else if(a==='new-season'||a==='edit-season')await seasonDialog(b.dataset.id);
 else if(a==='default-season'){const next=C.clone(state);next.meta.activeSeasonId=season;if(await save(next,'season','既定シーズンを '+state.seasons[season].name+' に変更'))render();}
 else if(a==='edit-teams')await editTeams();
 else if(a==='edit-checks')await editChecks();
 else if(a==='new-formation')await formationDialog();
 else if(a==='correct-team')await correctTeam(b.dataset.id,b.dataset.history);
 else if(a==='review-record')await linkDialog([b.dataset.id]);
 else if(a==='review-name')await linkDialog(Object.values(state.legacy).filter(r=>r.sourceName===b.dataset.name&&!r.memberId).map(r=>r.id));
 else if(a==='correct-alias')await correctAlias(b.dataset.id);
 else if(a==='resolve-issue')await issueDialog(b.dataset.id);
 else if(a==='add-contribution')await contributionDialog(b.dataset.id);
 else if(a==='backup')await backup();
 else if(a==='export'){await downloadExcel(state,season,b.dataset.format);toast('Excelを書き出しました');}
 else if(a==='commit-group-import')await commitGroupImport();
 else if(a==='team-csv')downloadTeamCSV(state,season);
 else if(a==='snapshot')snapshotDialog(b.dataset.id);
 else if(a==='person-audit'){auditMember=b.dataset.id;page='audit';render();}
 else if(a==='reload-audit')await loadLogs();
 else if(a==='more-audit')await loadLogs(true);
 }catch(e){toast(e.message,true);}});
async function commitCSV(){C.assert(importData,'CSVを選んでください');const date=$('#csv-date').value;C.assert(C.validDate(date),'取得日を指定してください');const existing=C.orderedSnapshots(state,season).find(x=>C.weekKey(x.date)===C.weekKey(date));const replace=!!existing;
 if(!confirm(`${state.seasons[season].name} / ${date}\n${importRows.length}件を登録します。新規人物 ${importRows.filter(r=>r.create).length}名。${replace?'\n同じ週の '+existing.date+' の記録を更新します。変更前の記録は訂正履歴に残ります。':''}`))return;
 const returning=C.autoReturnCandidates(state,season,date,importRows);const next=C.importSnapshot(state,{...importData,date,seasonId:season,rows:importRows,replace});if(await save(next,'csv',date+' 分CSVを取込：'+importData.fileName+' / '+importRows.length+'件 / 自動復帰 '+returning.length+'名'+(replace?'（同週の訂正）':''))){importRows=[];importData=null;render();}}
async function returnMember(mid){const m=state.members[mid];C.assert(m,'メンバーが見つかりません');C.assert(C.TEMP_STATUSES.includes(C.presenceStatus(m,season)),'一時離脱中のメンバーではありません');if(!confirm(m.name+' を在籍に戻しますか？'))return;
 const next=C.clone(state);C.setPresence(next,mid,season,'在籍',{date:C.today(),note:'手動復帰',source:'manual'});if(await save(next,'edit',m.name+' を手動で在籍に復帰'))render();}
async function addMember(){const d=await modalForm('メンバーを追加',`<label>ゲーム内名前<input name="name" required maxlength="100"></label><p class="unitnote">同名や旧名は既存メンバーで確認してください。</p>`,'追加する');if(!d)return;C.assert(!C.matchName(state,d.name).length,'同名・旧名の人物がすでにいます');const next=C.clone(state),m=C.newMember(d.name,season,C.today());next.members[m.id]=m;C.addAlias(next,m.id,m.name,'手動登録');if(await save(next,'member',m.name+' を新規登録')){page='members';detailId=m.id;render();}}
async function linkDialog(ids){C.assert(ids.length,'未紐付けの記録がありません');const r=state.legacy[ids[0]],d=await modalForm('元資料を人物に紐付け',`<p>${E(r.sourceName)} / ${ids.length}件</p><p class="subline">${E(r.sheet)} 行${r.row}：${E(JSON.stringify(r.values))}</p><div class="fields" style="margin-top:16px"><label>既存人物<select name="mid">${memberOptions(r.memberId||'')}</select></label><label>または、新規人物として登録する名前<input name="newName" placeholder="新規作成する場合のみ入力"></label><label class="checkline"><input type="checkbox" name="remember" value="yes" checked>この原資料名を今後のCSV照合にも使う</label><p class="unitnote">サブアカウントや同名の別人をまとめないよう、原資料を確認してください。複数記録でも値は上書きせず出典ごとに保持します。</p></div>`,'確認して紐付け');if(!d)return;C.assert(!(d.mid&&d.newName.trim()),'既存人物か新規登録のどちらか一方を指定してください');if(d.newName.trim())C.assert(!C.matchName(state,d.newName).length,'同名の人物が存在します');const next=C.linkLegacy(state,ids,d.mid,{createName:d.newName.trim(),seasonId:r.seasonId,remember:d.remember==='yes'});if(await save(next,'link',r.sourceName+' の元資料 '+ids.length+'件を紐付け'))render();}
async function issueDialog(id){const i=state.issues[id],d=await modalForm('確認内容を記録',`<p>${E(i.description)}</p><label>判断・補足<textarea name="note" required>${E(i.note)}</textarea></label><label>状態<select name="status">${options([['resolved','確認済み'],['open','要確認のまま']],i.status==='open'?'resolved':i.status)}</select></label>`);if(!d)return;const next=C.clone(state);Object.assign(next.issues[id],d,{reviewedAt:new Date().toISOString()});if(await save(next,'issue',i.kind+' の確認内容を記録'))render();}
async function seasonDialog(id){const old=state.seasons[id]||{name:'',start:'',end:''},d=await modalForm(id?'シーズンを編集':'新しいシーズン',`<div class="fields"><label>名称<input name="name" value="${E(old.name)}" placeholder="PK3 / S6" required></label><label>開始日<input name="start" type="date" value="${E(old.start)}"></label><label>終了日<input name="end" type="date" value="${E(old.end)}"></label>${!id?'<label class="checkline"><input type="checkbox" name="carry" value="yes" checked>表示中の在籍メンバーを引き継ぐ</label>':''}</div>`);if(!d)return;const next=C.clone(state),sid=id||C.uid();next.seasons[sid]={id:sid,name:d.name.trim(),start:d.start,end:d.end};if(!id&&d.carry==='yes')for(const m of membersInSeason()){if(m.memberships.filter(x=>x.seasonId===season).at(-1)?.status==='在籍')next.members[m.id].memberships.push({seasonId:sid,status:'在籍',since:d.start,note:'前シーズンから引継ぎ'});}C.validateState(next);if(await save(next,'season',d.name+' のシーズン設定を保存'))render();}
async function formationDialog(){const ms=membersInSeason(),d=await modalForm('隊編成をまとめて記録',`<div class="fields"><label>編成名<input name="name" required placeholder="開幕編成 / 戦線再編など"></label><label>編成開始日<input name="start" type="date" value="${C.today()}" required></label><label>編成メモ<textarea name="note" required placeholder="なぜこの編成にするか"></textarea></label><p class="unitnote">変更する人物だけ隊を変更してください。同日履歴がある人物は、人物詳細の「訂正」から変更できます。</p>${ms.map(m=>`<label>${E(m.name)}<input name="team_${m.id}" value="${E(currentTeam(m))}"></label>`).join('')}</div>`,'編成を保存');if(!d)return;C.assert(C.validDate(d.start),'開始日が不正です');let next=C.clone(state);const fid=C.uid(),teams=[...new Set(ms.map(m=>d['team_'+m.id].trim()).filter(Boolean))];next.formations[fid]={id:fid,seasonId:season,name:d.name,start:d.start,note:d.note,teams};for(const m of ms)next=C.editMember(next,m.id,{}, {seasonId:season,date:d.start,team:d['team_'+m.id],formationId:fid,teamNote:d.note});if(await save(next,'team',d.name+' の隊編成を保存'))render();}
async function correctTeam(mid,hid){const m=state.members[mid],old=m.teamHistory.find(x=>x.id===hid),d=await modalForm('隊履歴を訂正',`<div class="fields"><label>隊<input name="team" value="${E(old.team)}"></label><label>開始日<input name="date" type="date" required value="${E(old.date)}"></label><label>訂正理由<input name="note" required></label></div><p class="unitnote">訂正前の値は変更履歴に残ります。</p>`);if(!d)return;const next=C.clone(state),h=next.members[mid].teamHistory.find(x=>x.id===hid);Object.assign(h,d);if(await save(next,'team',m.name+' の隊履歴を訂正'))render();}
async function contributionDialog(mid){const d=await modalForm('貢献の事実を記録',`<div class="fields"><label>日付<input type="date" name="date" required value="${C.today()}"></label><label>区分<select name="category">${options(['門神担当','幹部活動','籠城管理','戦線管理','外交','攻城関連','新人フォロー','資料／ツール作成','その他'].map(x=>[x,x]),'')}</select></label><label>内容<textarea name="note" required></textarea></label></div>`);if(!d)return;const next=C.clone(state),id=C.uid();next.contributions[id]={id,memberId:mid,seasonId:season,...d};if(await save(next,'contribution',state.members[mid].name+' の貢献履歴を記録'))render();}
async function backup(){const b=demo?C.buildBackup(state,logs,revision):await store.backup();C.validateBackup(b);download('clan-ledger-backup-'+C.today()+'-r'+b.revision+'.json',b);toast('バックアップを書き出しました');return b;}
async function restore(b){const initial=Object.keys(state.members).length===0,d=await modalForm(initial?'初期データを登録':'バックアップから復元',`<p>読み込むデータ：${Object.keys(b.state.members).length}名 / ${Object.keys(b.state.snapshots).length}週次記録 / ${b.audit.length}編集ログ</p><p class="subline">${initial?'初期データまたはバックアップを共有DBへ登録します。':'現在の人物情報と履歴データを、このバックアップの時点へ置き換えます。現在DBにある編集ログは消しません。'}</p><label style="margin-top:15px">確認のため「${initial?'初期登録':'復元'}」と入力<input name="confirm" required autocomplete="off"></label>`,initial?'初期登録する':'復元する');if(!d)return;C.assert(d.confirm===(initial?'初期登録':'復元'),'確認文字が一致しません');const op=await ensureOperator();if(!op)return;if(!initial)await backup();const kind=initial&&b.audit.length===0?'initialize':'restore';if(await save(b.state,kind,initial?'初期データ・過去ログを登録':'バックアップ '+b.exportedAt+' を復元',b.audit)){season=state.meta.activeSeasonId;render();}}
function snapshotDialog(id){const s=state.snapshots[id];const html=`<h2>${E(s.date)} の週次記録</h2><p>${E(s.fileName)} · ${s.rows.length}名</p><div class="tablewrap" style="margin-top:15px"><table><thead><tr><th>当時の名前</th><th>現在の人物</th><th>今週戦功</th><th>今週活躍度</th></tr></thead><tbody>${s.rows.map(r=>`<tr><td>${E(r.name)}</td><td>${E(state.members[r.memberId]?.name)}</td><td>${N(r.meritWeek)}</td><td>${N(r.activityWeek)}</td></tr>`).join('')}</tbody></table></div>${s.versions.length?`<details class="details"><summary>訂正前の記録 ${s.versions.length}件</summary>${s.versions.map(v=>`<details><summary>${E(v.date)} · ${E(v.fileName)}</summary><pre>${E(JSON.stringify(v.rows,null,2))}</pre></details>`).join('')}</details>`:''}<form method="dialog" class="actions"><button>閉じる</button></form>`;$('#modal').innerHTML=html;$('#modal').showModal();}
let lastRosterMobile=isMobileRoster();
window.addEventListener('resize',()=>{const mobile=isMobileRoster();if(mobile!==lastRosterMobile){lastRosterMobile=mobile;memberColumns=null;applyRosterColumns(visibleRosterColumns());if(state&&page==='members'&&!detailId)render();}});
window.addEventListener('beforeunload',e=>{if(dirty||busy||importRows.length){e.preventDefault();e.returnValue='';}});
setInterval(()=>{if(state&&!demo&&store.hasSession()&&!busy&&!dirty&&!importRows.length&&document.visibilityState==='visible'&&!$('#modal').open)store.head().then(r=>{if(r.revision!==revision)return refresh();}).catch(e=>toast(e.message,true));},60000);
loginView();if(store.auth)refresh().catch(e=>loginView(e.authExpired?'利用セッションが終了しました。合言葉と操作者名を入力してください。':e.message));

async function correctAlias(id){const old=state.aliases[id],d=await modalForm('別名の紐付けを訂正',`<p>別名：${E(old.name)}</p><label>正しい人物<select name="mid" required>${memberOptions(old.memberId)}</select></label><label>訂正理由<input name="reason" required></label><p class="unitnote">過去CSVの紐付けは変わりません。必要な週のCSVを再取込して訂正してください。同じ名前を現在名に持つ別人がいると自動照合は停止します。</p>`);if(!d)return;C.assert(state.members[d.mid],'人物を選んでください');const next=C.clone(state);next.aliases[id].memberId=d.mid;next.aliases[id].source='手動訂正：'+d.reason;if(await save(next,'link','別名 '+old.name+' の紐付けを訂正：'+d.reason))render();}

async function editTeams(){const defs=C.teamDefs(state,season),fields=defs.map((t,i)=>`<label>第${i+1}隊の表示名<input name="name_${i}" maxlength="80" required value="${E(t.name)}"></label>`).join('');const d=await modalForm('隊名を編集',`<div class="fields">${fields}</div><p class="unitnote">内部IDは変更せず、表示名のみ更新します。隊員の所属履歴は維持されます。</p>`);if(!d)return;const names=defs.map((t,i)=>String(d['name_'+i]||'').trim());C.assert(names.every(Boolean)&&new Set(names).size===names.length,'隊名は重複しないように入力してください');const next=C.clone(state);next.teamSettings??={};next.teamSettings[season]=defs.map((t,i)=>({...t,name:names[i]}));if(await save(next,'team','隊名を変更'))render();}
async function editChecks(){const defs=C.checksFor(state,season);const d=await modalForm('シーズン進捗の項目',`<p class="subline">既存項目の名称は変えられます。項目の追加は最下段に入力してください。チェック実績は残ります。</p><div class="fields">${defs.map(x=>`<label>${E(x.id)}<input name="item_${E(x.id)}" required maxlength="80" value="${E(x.name)}"></label>`).join('')}<label>新しい項目名<input name="new_item" maxlength="80" placeholder="例：出生済"></label></div>`);if(!d)return;const items=defs.map(x=>({id:x.id,name:String(d['item_'+x.id]||'').trim()}));C.assert(items.every(x=>x.name),'項目名は空にできません');const added=String(d.new_item||'').trim();if(added)items.push({id:'check_'+C.uid().replaceAll('-',''),name:added});C.assert(new Set(items.map(x=>x.name)).size===items.length,'同じ項目名があります');const next=C.clone(state);next.checkDefinitions??={};next.checkDefinitions[season]=items;if(await save(next,'checks','シーズン進捗項目を更新'))render();}

function groupImportHtml(){if(!groupImportPreview)return '<p class="unitnote">取り込み前に一致／未一致を確認できます。既存の名簿・隊・役職は変更しません。</p>';const rs=groupImportPreview;const counts={update:rs.filter(r=>r.status==='update').length,same:rs.filter(r=>r.status==='same').length,skip:rs.filter(r=>r.status==='skip').length};return `<p class="subline">${E(groupImportFile)}：更新 ${counts.update}アカウント／変更なし ${counts.same}アカウント／保留 ${counts.skip}行</p><div class="tablewrap"><table><thead><tr><th>行</th><th>Discord ID</th><th>名簿の人物</th><th>現在</th><th>取込先</th><th>結果</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${r.row}</td><td>${E(r.id)}</td><td>${E(r.name||'—')}</td><td>${E(r.before||'—')}</td><td>${E(r.group||'—')}</td><td>${E(r.reason||({update:'更新',same:'変更なし'}[r.status]))}</td></tr>`).join('')}</tbody></table></div><div class="actions" style="margin-top:14px">${button('一致した '+counts.update+'アカウントを共有DBへ保存','commit-group-import',counts.update&&!demo?'':'disabled','primary')}</div><p class="unitnote">同じDiscord IDの複数アカウントはすべて対象です。Excel内で同じIDに異なるグループが指定されていた場合は保留します。ファイルにないメンバーは変更しません。</p>`;}
async function commitGroupImport(){C.assert(groupImportPreview,'Excelを選んでください');const valid=groupImportPreview.filter(r=>r.status==='update');C.assert(valid.length,'更新対象がありません');if(!confirm(`${valid.length}アカウントのグループ所属を更新します。\n未一致・Excel内で指定が競合しているIDは更新しません。実行しますか？`))return;const {next,count}=applyGroupImport(state,groupImportPreview);if(await save(next,'group',`グループ一括取込 ${groupImportFile}：${count}アカウント更新`)){groupImportPreview=null;groupImportFile='';render();}}
