import {membersIn,metrics,teamAt,orderedSnapshots,today,teamId,teamLabel,memberRank,positionRank} from './core.js';
const xml=v=>String(v??'').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function col(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;}
function idx(c){let n=0;for(const x of c)n=n*26+x.charCodeAt(0)-64;return n-1;}
const refWar=(s,id)=>Object.values(s.legacy).find(r=>r.memberId===id&&r.sheet==='Sheet1')?.values['編成参考戦功（単位・時点未確認）']??null;
export function exportTables(s,season,format){const ms=membersIn(s,season).sort((a,b)=>memberRank(a)-memberRank(b)||a.name.localeCompare(b.name,'ja')),hist=Crows(s,season);const team=[['ゲーム内名前','戦功総量（実数）','隊','今週戦功（実数）','前週差（実数）','編成参考戦功（単位・時点未確認）','ゲーム内グループ','内部ID','取得日','隊内役職','一門役職','運営グループ'],...ms.slice().sort((a,b)=>{const at=teamId(s,season,teamAt(a,season)),bt=teamId(s,season,teamAt(b,season));const ai=Number(at.match(/^team(\d+)$/)?.[1]||99),bi=Number(bt.match(/^team(\d+)$/)?.[1]||99);return ai-bi||positionRank(a,season)-positionRank(b,season)||a.name.localeCompare(b.name,'ja');}).map(m=>{const v=metrics(s,m.id,season);return [m.name,v.current?.meritTotal??null,teamLabel(s,season,teamAt(m,season)),v.current?.meritWeek??null,v.delta,refWar(s,m.id),v.current?.gameGroup||'',m.id,v.date||'',m.teamPositions?.[season]||'一般',m.leadership||'一般',m.group||''];})];
 if(format==='team')return [{name:'隊分け表',rows:team,widths:[25,23,15,22,22,44,23,40,16,15,15,20]}];
 if(format==='okiku'){const checks=m=>m.checks[season]||{};return [
 {name:season==='s5'?'S5メンバ':'メンバ名簿',rows:[['ゲーム名前','discord名前','discordID',s.seasons[season].name+'ディスコ加入','自己紹介','部隊編成','小隊加入','ざっくり元所属とか経緯','現在の隊','役割','元所属','加入経緯','自由記述メモ','内部ID','所属状態'],...ms.map(m=>[m.name,m.discordName,m.discordId,checks(m).discord,checks(m).intro,checks(m).roster,checks(m).squad,m.originContext,teamAt(m,season),m.role,m.origin,m.joinHistory,m.note,m.id,m.memberships.filter(x=>x.seasonId===season).at(-1)?.status])],widths:[25,26,32,28,14,14,14,48,15,22,25,40,48,40,14]},
 {name:'Sheet1',rows:team,widths:[25,23,15,22,22,44,23,40,16,15,15,20]},
 {name:'週次履歴',rows:hist,widths:[16,25,25,22,22,22,22,15,20,20,40]},
 {name:'隊履歴',rows:[['ゲーム名前','シーズン','開始日','隊','編成メモ','内部ID'],...Object.values(s.members).flatMap(m=>m.teamHistory.map(t=>[m.name,s.seasons[t.seasonId]?.name,t.date,t.team,t.note,m.id]))],widths:[25,20,16,15,50,40]}
 ];}
 const result=[{name:'現在実績',rows:[['名前','隊','戦功今週（実数）','戦功総量（実数）','前週戦功（実数）','前週差（実数）','活躍度今週','活躍度総量','威信','所属地方','ゲーム内グループ','内部ID','取得日'],...ms.map(m=>{const v=metrics(s,m.id,season);return [m.name,teamAt(m,season),v.current?.meritWeek??null,v.current?.meritTotal??null,v.previous?.meritWeek??null,v.delta,v.current?.activityWeek??null,v.current?.activityTotal??null,v.current?.prestige??null,v.current?.region||'',v.current?.gameGroup||'',m.id,v.date||''];})],widths:[25,15,24,24,24,24,22,22,15,20,24,40,16]}];
 for(const name of ['S4メンバー','S4メンバー (補給)','生存確認','S4メンバー (覇業管理)']){
  const source=Object.values(s.sources).flatMap(x=>x.sheets||[]).find(x=>x.name===name);const rows=[];
  if(source){for(const r of source.rows){if(r.row>200)continue;while(rows.length<r.row)rows.push([]);for(const [c,v] of Object.entries(r.cells))rows[r.row-1][idx(c)]=v.value;}}
  for(const r of Object.values(s.legacy).filter(r=>r.sheet===name)){while(rows.length<r.row)rows.push([]);for(const [c,v] of Object.entries(r.raw))rows[r.row-1][idx(c)]=v;rows[r.row-1][idx(r.column||'A')]=s.members[r.memberId]?.name||r.sourceName;}
  // Original side-by-side layouts; do not reinterpret unlabeled hagyo/survival cells.
  result.push({name,rows:rows.map(row=>Array.from({length:Math.max(22,row.length)},(_,i)=>row[i]??null)),widths:Array.from({length:22},(_,i)=>[0,7,15].includes(i)?26:18),headerRows:[2,3]});
 }
 result.push({name:'照合台帳',rows:[['原資料名','現在の人物','シート','行','区分','照合状態','内部ID','原資料の値'],...Object.values(s.legacy).map(r=>[r.sourceName,s.members[r.memberId]?.name||'',r.sheet,r.row,r.group,r.match,r.memberId||'',JSON.stringify(r.values)])],widths:[25,25,28,10,35,20,40,80]});
 return result;
}
function Crows(s,season){return [['取得日','ゲーム名前（取得時）','ゲーム名前（現在）','戦功今週','戦功総量','活躍度今週','活躍度総量','威信','所属地方','ゲーム内グループ','内部ID'],...orderedSnapshots(s,season).flatMap(x=>x.rows.map(r=>[x.date,r.name,s.members[r.memberId]?.name,r.meritWeek,r.meritTotal,r.activityWeek,r.activityTotal,r.prestige,r.region,r.gameGroup,r.memberId]))];}
function sheetXML({rows,widths=[],headerRows=[1]}){const ncols=Math.max(1,...rows.map(r=>r.length)),end=col(ncols-1)+Math.max(1,rows.length);return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:${end}"/><sheetViews><sheetView workbookViewId="0"><pane ySplit="${Math.max(...headerRows)}" topLeftCell="A${Math.max(...headerRows)+1}" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="22"/><cols>${Array.from({length:ncols},(_,i)=>`<col min="${i+1}" max="${i+1}" width="${widths[i]||22}" customWidth="1"/>`).join('')}</cols><sheetData>${rows.map((r,i)=>`<row r="${i+1}"${headerRows.includes(i+1)?' ht="34" customHeight="1"':''}>${r.map((v,j)=>v==null?'':typeof v==='number'&&Number.isFinite(v)?`<c r="${col(j)}${i+1}" s="${headerRows.includes(i+1)?1:3}"><v>${v}</v></c>`:`<c r="${col(j)}${i+1}" t="inlineStr" s="${headerRows.includes(i+1)?1:2}"><is><t xml:space="preserve">${xml(v)}</t></is></c>`).join('')}</row>`).join('')}</sheetData>${headerRows.length===1?`<autoFilter ref="A1:${end}"/>`:''}<pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/></worksheet>`;}
export async function makeXlsx(tables,JSZip,templateBytes){const zip=await JSZip.loadAsync(templateBytes);const workbook=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><bookViews><workbookView/></bookViews><sheets>${tables.map((t,i)=>`<sheet name="${xml(t.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`;
 // A clean artifact-tool-authored template supplies package metadata. Only output data is inserted here.
 zip.file('xl/workbook.xml',workbook);zip.file('xl/_rels/workbook.xml.rels',`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${tables.map((t,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId${tables.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`);
 zip.file('[Content_Types].xml',`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${tables.map((t,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`);
 zip.file('_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
 // Stable styles independent of source workbook's style IDs.
 zip.file('xl/styles.xml',`<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Yu Gothic"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Yu Gothic"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF173E42"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="4"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="49" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="3" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`);
 for(const name of Object.keys(zip.files)){if(/^(docProps\/|xl\/(worksheets\/|theme\/|sharedStrings.xml|calcChain.xml))/.test(name))zip.remove(name);}
 tables.forEach((t,i)=>zip.file(`xl/worksheets/sheet${i+1}.xml`,sheetXML(t)));return zip.generateAsync({type:'uint8array',compression:'DEFLATE'});}
function download(name,bytes,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([bytes],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),15000);}
export async function downloadExcel(s,season,format){const response=await fetch('./templates/export-base.xlsx');if(!response.ok)throw new Error('Excel出力用テンプレートがありません。webフォルダをすべて公開してください');const tables=exportTables(s,season,format);const bytes=await makeXlsx(tables,window.JSZip,await response.arrayBuffer());download(`clan-ledger-${format}-${today()}.xlsx`,bytes,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}
export function downloadTeamCSV(s,season){const rows=exportTables(s,season,'team')[0].rows;const text='\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');download('clan-ledger-teams-'+today()+'.csv',text,'text/csv;charset=utf-8');}
